### ISSUE TITLE
Add call for badging / splats to apps sdk

### ISSUE THREAD

**Issue by TheJosephBarnes** [purecloudlabs/skype-for-business-purecloud-app#2]
We'll likely need to start adding a few calls to the apps sdk to allow for some UX-intended functionality for the skype work; the simplest call that we know is needed is to add one for a splat on the sidebar icon when new skype messages comes in.

**Comment by ericlifka** [comment]
The pure cloud SDK side of this work is done, using this ticket to track the Skype app side of showing those badges.
